### ISSUE TITLE
Role adder (idk name) not themed

### ISSUE THREAD

**Issue by ghost** [LuckFire/Theme-Source#2]
![image](https://user-images.githubusercontent.com/71416098/97778844-a3b7f900-1bac-11eb-9dc0-bf5a816cc579.png)

**Comment by LuckFire** [comment]
Seems you closed the issue, is it still not themed or?

**Comment by ghost** [comment]
i closed it because thats the themed already (i saw no difference with default cuz i am color blind), i checked the hex of it, its correct. it was my bad

**Comment by ghost** [comment]
i checked dark discord with the old source and the new source (snapperito), role adder is supposed to use (--background-secondary) instead of (--background-secondary-alt), idk if this was intentional but i'd like to point this out
