### ISSUE TITLE
AMOLED-cord issue.

### ISSUE THREAD

**Issue by Burger-Gaming** [LuckFire/Theme-Source#4]
The spoiler text blends in with the background slightly, making it difficult to see whether or not it's a spoiler or just blank text. Make it so that the color is brighter.
![image](https://user-images.githubusercontent.com/69328615/115097809-8e7c2000-9ee9-11eb-988c-56ea62eeef7e.png)

**Comment by LuckFire** [comment]
fixed this issue on amoled-cord
